// created by Kieran Watson

const { encrypt } = require("../../security");
const Security = require("../../security");
const MoPi = require("../../security")

const algorithm = 'aes-256-ctr';
const secretKey = 'vOVH6sdmpNWjRRIqCc7rdxs01lwHzfr3';
test('Check that Hello World! can be encrypted and then decrypted', () => {
    hash = Security.encrypt("Hello World!", algorithm, secretKey);
    expect(Security.decrypt(hash, algorithm, secretKey)).toBe("Hello World!");
});

test('Check that @:?.,-! can be encrypted and then decrypted', () => {
    hash = Security.encrypt("@:?.,-!", algorithm, secretKey);
    expect(Security.decrypt(hash, algorithm, secretKey)).toBe("@:?.,-!");
});

test('Check that a can be encrypted and then decrypted', () => {
    hash = Security.encrypt("a", algorithm, secretKey);
    expect(Security.decrypt(hash, algorithm, secretKey)).toBe("a");
});

test('Check that 1 paragraph of Lorem Ipsum can be encrypted and then decrypted', () => {
    hash = Security.encrypt("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ultrices convallis magna et imperdiet. Ut maximus cursus libero, vel tempus nibh condimentum et. Integer orci odio, scelerisque quis elementum sed, gravida semper ipsum. In et efficitur enim. Nulla ultricies dolor ac justo tristique aliquam. Mauris vel fringilla sapien, at eleifend neque. Suspendisse id est libero. Sed fermentum odio a mauris cursus, at dignissim mauris tempus. Integer tincidunt enim ut leo ultrices pretium.", algorithm, secretKey);
    expect(Security.decrypt(hash, algorithm, secretKey)).toBe("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ultrices convallis magna et imperdiet. Ut maximus cursus libero, vel tempus nibh condimentum et. Integer orci odio, scelerisque quis elementum sed, gravida semper ipsum. In et efficitur enim. Nulla ultricies dolor ac justo tristique aliquam. Mauris vel fringilla sapien, at eleifend neque. Suspendisse id est libero. Sed fermentum odio a mauris cursus, at dignissim mauris tempus. Integer tincidunt enim ut leo ultrices pretium.");
});

test('Check that 5 paragraph of Lorem Ipsum can be encrypted and then decrypted', () => {
    hash = Security.encrypt('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ultrices convallis magna et imperdiet. Ut maximus cursus libero, vel tempus nibh condimentum et. Integer orci odio, scelerisque quis elementum sed, gravida semper ipsum. In et efficitur enim. Nulla ultricies dolor ac justo tristique aliquam. Mauris vel fringilla sapien, at eleifend neque. Suspendisse id est libero. Sed fermentum odio a mauris cursus, at dignissim mauris tempus. Integer tincidunt enim ut leo ultrices pretium. Cras nec sapien ac sem blandit posuere. Morbi id lorem aliquet quam sodales bibendum. Pellentesque condimentum id orci vitae laoreet. Duis sodales nibh et tempus convallis. Duis hendrerit ipsum quis justo rhoncus fermentum. Pellentesque faucibus leo nec turpis accumsan, et faucibus lectus auctor. Mauris nec consectetur urna. Cras nec eros vitae nisl dapibus ultrices. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec sagittis augue ac eros tincidunt, ultrices vulputate metus rutrum. Aliquam interdum malesuada risus, vel rutrum sem varius id. Sed ac orci nec ipsum luctus imperdiet. Mauris porta lectus eu velit cursus, id porta nulla sollicitudin. Aliquam non hendrerit est. Integer nisl purus, pulvinar vel odio consectetur, ultricies rhoncus orci. In hac habitasse platea dictumst. Suspendisse enim turpis, semper sed mauris eu, scelerisque dictum libero. Phasellus id est eget mauris pulvinar pellentesque ac vitae velit. Praesent blandit neque justo, sed eleifend leo vulputate eget. Nulla id sapien a libero dictum ornare. Praesent eleifend tristique vulputate. Pellentesque sit amet erat id metus porta pulvinar. Nullam blandit ornare dui, in vehicula erat laoreet at. Interdum et malesuada fames ac ante ipsum primis in faucibus.Cras sodales feugiat condimentum. In hac habitasse platea dictumst. Fusce ut diam maximus, hendrerit velit non, malesuada urna. Cras id fermentum magna, vitae egestas orci. Nulla vel fermentum lorem. Ut sit amet consectetur diam. Donec sed rhoncus massa. In aliquam ligula in dui laoreet, eu gravida erat facilisis. Mauris lacinia facilisis erat, sit amet vehicula quam euismod quis. Morbi fringilla risus nec lorem faucibus maximus.Mauris posuere elementum arcu ut egestas. In justo nisi, blandit in mattis non, lacinia eget nisi. Integer pulvinar pulvinar est sit amet vulputate. Nunc sed mi sit amet sapien accumsan feugiat. Morbi bibendum magna a ultrices cursus. Maecenas ac vulputate urna. Nulla mattis tortor erat, id commodo ante vehicula et.', algorithm, secretKey);
    expect(Security.decrypt(hash, algorithm, secretKey)).toBe('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ultrices convallis magna et imperdiet. Ut maximus cursus libero, vel tempus nibh condimentum et. Integer orci odio, scelerisque quis elementum sed, gravida semper ipsum. In et efficitur enim. Nulla ultricies dolor ac justo tristique aliquam. Mauris vel fringilla sapien, at eleifend neque. Suspendisse id est libero. Sed fermentum odio a mauris cursus, at dignissim mauris tempus. Integer tincidunt enim ut leo ultrices pretium. Cras nec sapien ac sem blandit posuere. Morbi id lorem aliquet quam sodales bibendum. Pellentesque condimentum id orci vitae laoreet. Duis sodales nibh et tempus convallis. Duis hendrerit ipsum quis justo rhoncus fermentum. Pellentesque faucibus leo nec turpis accumsan, et faucibus lectus auctor. Mauris nec consectetur urna. Cras nec eros vitae nisl dapibus ultrices. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec sagittis augue ac eros tincidunt, ultrices vulputate metus rutrum. Aliquam interdum malesuada risus, vel rutrum sem varius id. Sed ac orci nec ipsum luctus imperdiet. Mauris porta lectus eu velit cursus, id porta nulla sollicitudin. Aliquam non hendrerit est. Integer nisl purus, pulvinar vel odio consectetur, ultricies rhoncus orci. In hac habitasse platea dictumst. Suspendisse enim turpis, semper sed mauris eu, scelerisque dictum libero. Phasellus id est eget mauris pulvinar pellentesque ac vitae velit. Praesent blandit neque justo, sed eleifend leo vulputate eget. Nulla id sapien a libero dictum ornare. Praesent eleifend tristique vulputate. Pellentesque sit amet erat id metus porta pulvinar. Nullam blandit ornare dui, in vehicula erat laoreet at. Interdum et malesuada fames ac ante ipsum primis in faucibus.Cras sodales feugiat condimentum. In hac habitasse platea dictumst. Fusce ut diam maximus, hendrerit velit non, malesuada urna. Cras id fermentum magna, vitae egestas orci. Nulla vel fermentum lorem. Ut sit amet consectetur diam. Donec sed rhoncus massa. In aliquam ligula in dui laoreet, eu gravida erat facilisis. Mauris lacinia facilisis erat, sit amet vehicula quam euismod quis. Morbi fringilla risus nec lorem faucibus maximus.Mauris posuere elementum arcu ut egestas. In justo nisi, blandit in mattis non, lacinia eget nisi. Integer pulvinar pulvinar est sit amet vulputate. Nunc sed mi sit amet sapien accumsan feugiat. Morbi bibendum magna a ultrices cursus. Maecenas ac vulputate urna. Nulla mattis tortor erat, id commodo ante vehicula et.');
});